# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180326_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.IntegerField(max_length=15, verbose_name='\u624b\u673a'),
        ),
    ]
