# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-01 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180326_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='fa_type',
            new_name='fav_type',
        ),
    ]
