# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
