# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180413_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, max_length=11, null=True),
        ),
    ]
