# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180413_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
