# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180413_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='index',
            field=models.IntegerField(default=50, verbose_name='\u987a\u5e8f'),
        ),
    ]
