# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180413_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
    ]
